services:
  - type: web
    name: insta-loader-web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn InstaLoaderWeb.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: InstaLoaderWeb.settings
      - key: SECRET_KEY
        generateValue: true
